name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      - name: Build
        run: mvn -B package
      - name: Docker Login
        if: ${{ github.event_name != 'pull_request'}}
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
      - name: Push image
        if: ${{ github.event_name != 'pull_request'}}
        run: mvn package -Dquarkus.container-image.push

  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      - name: Build Native
        run: mvn -B package -Pnative -Dquarkus.container-image.build -Dquarkus.container-image.tag=main-native
      - name: Docker Login
        if: ${{ github.event_name != 'pull_request'}}
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
      - name: Push Native Image
        if: ${{ github.event_name != 'pull_request'}}
        run: mvn -B package -Pnative -Dquarkus.container-image.push -Dquarkus.native.reuse-existing=true -Dquarkus.container-image.tag=main-native
