name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Docker Login
        if: ${{ github.event_name != 'pull_request'}}
        run: echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
      - name: Build and push Docker image
        if: ${{ github.event_name != 'pull_request'}}
        run: |
          docker build -t ghcr.io/${{github.repository}}:latest .
          docker push ghcr.io/${{github.repository}}:latest
